### PR TITLE
Add attributions

### PR DESCRIPTION
**Pull request by tfalders**
Addresses SWDEV-308187.

I've added copyright notices for LAPACK and MAGMA to our license file, and included the license file in our readthedocs documentation. I've also added a copyright notice to the file that was flagged by our scan.

### CODE REVIEW

**Review by jzuniga-amd — APPROVED** [review]
As per our last discussion, it looks good to me.

**Review by doctorcolinsmith — APPROVED** [review]

**Review by cgmb — APPROVED** [review]

**Review by saadrahim — APPROVED** [review]
adding m2r2 should be checked. Not sure if readthedocs is including that.

**Comment by tfalders** [comment]
> adding m2r2 should be checked. Not sure if readthedocs is including that.

The readthedocs appears to be building correctly. We've tested m2r2 previously with the hipSOLVER documentation too.

**Comment by cgmb** [comment]
> adding m2r2 should be checked. Not sure if readthedocs is including that.

ReadTheDocs uses that requirements file to determine what packages we need. We configured it that way in [.readthedocs.yaml](https://github.com/ROCmSoftwarePlatform/rocSOLVER/blob/fec75b57a438e6695c61b055cce508559bcf653b/.readthedocs.yaml#L14).

**Comment by cgmb** [comment]
This will needed in master for 5.0.

**Pull request merged**
