### PR TITLE
Fix memory model tests

### PR DESCRIPTION
**Pull request by jzuniga-amd**
The optimized GETRF requires less memory than before and our memory_model tests were failing. Here is a quick fix.

### CODE REVIEW

**Comment by cgmb** [comment]
SWDEV-313490.

This is a fragile test and we're not running it on CI. Ideally we'd fix both those problems, but the latter is the easier of the two.

I'm thinking of changing the test name to `checkin_misc_MANAGED_MEMORY` and our psdb test filter to `checkin*` rather than `*checkin_lapack*`.

**Review by tfalders — APPROVED** [review]

**Comment by jzuniga-amd** [comment]
Yes, sounds good to me...
I was wondering why we did not catch the error with the PR...
So, enabling this test on CI with the new naming is fine. 
If you can do the modifications in this PR we can merge them all together

**Comment by cgmb** [comment]
I've opened https://github.com/jzuniga-amd/rocSOLVER/pull/7 with my suggested changes.

**Review by cgmb — APPROVED** [review]
LGTM, but let's just be sure the tests work on CI before merging.

**Pull request merged**
