### PR TITLE
Disable git hook auto-install

### PR DESCRIPTION
**Pull request by cgmb**
Install hooks with `./install.sh --hooks`.

Making this process explicit may prevent surprises and frustration.

### CODE REVIEW

**Review by tfalders — CHANGES_REQUESTED** [review]
LGTM, but I'm a little iffy on deleting the separate install script. I'd prefer if it were more like how we handle building the docs, with separate scripts that can be called through install.sh for convenience.

**Comment by jzuniga-amd** [comment]
Same here, I think it is better to keep the hook install script. As per previous discussions, we need that ALL the functionality provided by the install.sh script can be achieved other ways. To build the library,  we have cmake + make.  To build the docs, we have run_doc.sh. To install hooks, we need something in case the install.sh is deprecated (any one can make the links manually, but I prefer to have the script).

**Comment by cgmb** [comment]
I deleted it because it wasn't used or mentioned anywhere. Would we prefer to just remove the auto-install from install.sh and change the README to say run `.githooks/install`?

**Comment by cgmb** [comment]
I think this addresses your concerns, and I like the simplicity. Thoughts?

CI failures are due to being unable to access `/dev/dri`. I assume there's a machine that needs rebooting.

**Review by tfalders — APPROVED** [review]
LGTM!

**Review by jzuniga-amd — APPROVED** [review]
LGTM

**Pull request merged**
