### PR TITLE
Enable docs build on CI and minor fixes

### PR DESCRIPTION
**Pull request by cgmb**
This is a rollup of the various docs changes I've made over the past month or so.

Summary:
- Minor fixups of typos and broken links
- Moved deprecated items to their own section at the bottom of the page
- Enabled the docs build on the CI
- `./install.sh --docs` now prints clickable links to the built docs

### CODE REVIEW

**Comment by cgmb** [comment]
There's now a Documentation link on the sidebar in Jenkins that you can click to see the docs associated with a given build. For this PR, that the static build page is: http://math-ci.rocm.amd.com/job/compute-rocm-dkms-no-npi-hipclang/job/Static%20Analysis/job/rocSOLVER/job/PR-175/

ci_docs

**Review by jzuniga-amd — COMMENTED** [review]
Looks good to me!
I would just add a comment in the section Types of the userguide_api.rst before jumping right away to additional types; something like this:

Types
=====

rocSOLVER uses defined types and enumerations of the rocBLAS API. For more information see the  `rocBLAS types <https://rocblas.readthedocs.io/en/latest/api.html#types>`_.

Additional Types
--------------------

These are types that extend the rocBLAS API
...

**Review by jzuniga-amd — APPROVED** [review]
LGTM

**Review by tfalders — APPROVED** [review]
LGTM!

**Pull request merged**
