### PR TITLE
Fixed broken link

### PR DESCRIPTION
**Pull request by spolifroni-amd**

### CODE REVIEW

**Review by cgmb — COMMENTED** [review]
If we're tagging a new commit hash for the ROCm 6.2.1 release, we need to update the changelog and version number.

**Comment by spolifroni-amd** [comment]
> If we're tagging a new commit hash for the ROCm 6.2.1 release, we need to update the changelog and version number.

I don't quite understand what you mean by this. This was just a broken link that was fixed.

**Review by samjwu — CHANGES_REQUESTED** [review]
I think this should be a cherry pick of https://github.com/ROCm/rocSOLVER/pull/813

**Comment by spolifroni-amd** [comment]
> I think this should be a cherry pick of #813

This is a cherry pick of 813.

**Pull request closed without merging**
