### PR TITLE
Add rtest.xml configuration for rtest.py

### PR DESCRIPTION
**Pull request by eidenyoshida**

### CODE REVIEW

**Review by lawruble13 — APPROVED** [review]
Looks good to me! As mentioned in other threads the `DOCTYPE` declaration as-is will not work for Windows. However, it isn't used for verification yet, so it should be safe to either remove or leave in place. As we progress further with this system, this should become a PUBLIC DTD, which should be safe for Windows and Linux.

**Review by cgmb — COMMENTED** [review]
This change conflicts with the `rtest.xml` included in #282, which is used on Windows and was modeled on rocblas. It's unclear to me how the conflict should be resolved.

**Comment by eidenyoshida** [comment]
I think this rtest.xml is compatible with changes in #282. If #282 is being merged soon then this PR can wait and any kinks can be worked out

**Comment by cgmb** [comment]
Can I drop the DTD so it works on Windows?

**Comment by lawruble13** [comment]
The DTD isn't used for anything yet, it can safely be dropped.

**Review by cgmb — APPROVED** [review]
I need to fix merge conflicts in #282 anyway, so I'm fine with this going in first.

**Review by tfalders — APPROVED** [review]
LGTM, though CI seems to be failing for some reason.

**Review by jzuniga-amd — APPROVED** [review]
LGTM

**Comment by cgmb** [comment]
> LGTM, though CI seems to be failing for some reason.

I think now even our release mode binary is too large to link when we build for all supported architectures and include the small matrix optimizations. I like seeing green checkmarks, so I'll re-run the tests with noOptimizations.

**Pull request merged**
