### PR TITLE
Consistent ordering for template arguments

### PR DESCRIPTION
**Pull request by tfalders**
Establishes a consistent ordering for typename S and bool BATCHED template arguments across the library. In summary:

- typename S always follows typename T.
- Test functions and _impl functions that do not have an argument of type S will use `using S = decltype(std::real(T{}));` instead of a template argument.
- bool BATCHED always precedes typename T in `getMemorySize` functions.

### CODE REVIEW

**Review by cgmb — APPROVED** [review]

**Comment by doctorcolinsmith** [comment]
I think this is OK, but please check that the template changes won't trigger a breaking ABI change on the public symbols.

**Comment by tfalders** [comment]
> I think this is OK, but please check that the template changes won't trigger a breaking ABI change on the public symbols.

I don't think rocSOLVER exports any template methods, so we should be fine.

**Review by jzuniga-amd — APPROVED** [review]
LGTM.
Nice! Good to finally have this sorted out library-wide...

**Comment by tfalders** [comment]
Looks like, other than a false failure, CI was passing. I'll resolve the conflicts and then merge the PR.

**Pull request merged**
