### PR TITLE
Copyright Header Fix

### PR DESCRIPTION
**Pull request by jibrealkhan**
Added appropriate BSD2 copyright headers to files.
Some files contain both BSD3 and BSD3 headers.
[SWDEV-404616]

### CODE REVIEW

**Review by cgmb — APPROVED** [review]
Excellent work. I checked every header you changed and they all look good to me.

The one thing still needed is to update the reformat-files script:
https://github.com/ROCmSoftwarePlatform/rocSOLVER/blob/71a255a5208a67c3b6d259aa90e336a5e0b3a716/scripts/reformat-files#L60-L61

**Review by qjojo — APPROVED** [review]

**Comment by tfalders** [comment]
Looks good, though I think we're missing the newly added files from https://github.com/ROCmSoftwarePlatform/rocSOLVER/pull/597. @jibrealkhan Would you be kindly add them in?

**Comment by cgmb** [comment]
> Looks good, though I think we're missing the newly added files from #597. @jibrealkhan Would you be kindly add them in?

@tfalders, you'll need to revisit those files to fix the Windows build anyway. I'm fine with @jibrealkhan just updating the reformat-files script.

**Review by tfalders — APPROVED** [review]

**Comment by tfalders** [comment]
This PR only affects comments in the files, so we should be okay to force the merge. @cgmb Care to do the honours?

EDIT: Oh right, the script still needs to be updated...

**Comment by tfalders** [comment]
> @tfalders, you'll need to revisit those files to fix the Windows build anyway. I'm fine with @jibrealkhan just updating the reformat-files script.

I've opened a PR on @jibrealkhan's fork to update the copyright headers for the new files, and added the fix for the Windows build to #600.

**Review by jzuniga-amd — APPROVED** [review]

**Pull request merged**
