### PR TITLE
Updating rocBLAS interface for syrk/syr2k/syrkx

### PR DESCRIPTION
**Pull request by daineAMD**
Reference changes to [rocblas-internal PR #1684](https://github.com/rocmsoftwareplatform/rocblas-internal/pull/1684). noCI for now as I'm these changes will need some discussion if we want to move forward with them or if we want to go a different direction.

### CODE REVIEW

**Comment by daineAMD** [comment]
rocBLAS changes should be good-to-go. Will wait for approval here before I go ahead with the merges to avoid versioning issues as much as possible.
After this I'm planning 1 more PR each to rocBLAS/rocSOLVER to clean up the rest of the interface.

**Comment by daineAMD** [comment]
Hoping to get an approval from rocSOLVER people here so I can go ahead with the rocBLAS merge. Thanks!

**Review by tfalders — APPROVED** [review]
LGTM! Thanks for working on this @daineAMD! I'm really looking forward to the interface between rocSOLVER and rocBLAS stabilizing.

**Comment by daineAMD** [comment]
Great, I've merged the rocBLAS PR and will monitor CI on this tonight/tomorrow. Thanks!

**Review by cgmb — APPROVED** [review]
I had hoped I could find the time to review the ABI impact of using C++ symbols for this, but the change is a major step forward regardless. If the rocBLAS side has been merged, then the rocSOLVER side should be going in as well.

Thanks, Daine!

**Pull request merged**
