### PR TITLE
Add benchmark scripts for performance tracking

### PR DESCRIPTION
**Pull request by cgmb**
To generate benchmark data, first build `rocsolver-bench`, then
```bash
pip3 install pandas
export PATH="/path/to/rocsolver-bench/dir:$PATH"
./scripts/perf/benchmark-suite
```

The resulting output can be found in `scripts/perf/rocsolver-benchmarks`.

### CODE REVIEW

**Comment by RobsonRLemos** [comment]
I have tested the benchmark-suite script and the generated datasets for the specified functions are working fine in the Performance Tracking System (PTS). The code is fine and it is written in such a way that more functions can be added in the near future. Thanks Cory for the first version of the implementation for the integration of rocSolver with the PTS system.

**Review by RobsonRLemos — APPROVED** [review]
The current implementation for the benchmark-suite is generating the needed datasets for the PTS system. With the current functionality the benchmark-suite can also be integrated in the near future with the CI system. Also the way the code is organized new functions can be added in the next versions of the implementation.

**Review by qjojo — APPROVED** [review]
Looks correct and maintainable 👍

**Review by tfalders — APPROVED** [review]
Nice job!

**Pull request merged**
