### PR TITLE
Amd feature targetid

### PR DESCRIPTION
**Pull request by eidenyoshida**

### CODE REVIEW

**Comment by cgmb** [comment]
Is this the full change for SWDEV-243249 in ROCm 4.0, or is there more to come?

**Comment by tfalders** [comment]
> Is this the full change for SWDEV-243249 in ROCm 4.0, or is there more to come?

I think we will still need to edit install.sh and the cmake files to add some options for xnack using the new syntax (I believe this PR only removes the old syntax), but that can probably wait until after the testing is completed.

**Comment by eidenyoshida** [comment]
You can ignore the 'hipclang-targetid-experimental' failures, those are an old experimental ci run. This PR has passed the precheckin tests on CI

**Review by tfalders — APPROVED** [review]
LGTM!

**Review by jzuniga-amd — APPROVED** [review]
Looks good, please squash and merge!

**Pull request merged**
