### PR TITLE
Check if HIP_RUNTIME equals ROCclr or rocclr

### PR DESCRIPTION
**Pull request by eidenyoshida**

### CODE REVIEW

**Comment by eidenyoshida** [comment]
> Would a case-insensitive string comparison be appropriate? Admittedly, the question is somewhat academic, as I'm not sure that's actually any cleaner in CMake.
> 
> It's fine as is. I just wonder if that would avoid having to revisit this change in the future.

A similar comment was made in rocFFT. I can implement whichever you prefer.
https://github.com/ROCmSoftwarePlatform/rocFFT-internal/pull/215

**Comment by cgmb** [comment]
I would prefer the `TOLOWER` version.

**Comment by cgmb** [comment]
Awesome. It still needs to go through CI checks before merging, but the change looks good.

**Comment by cgmb** [comment]
While there are CI failures, they are unrelated. Squash and merge at your leisure.

**Pull request merged**
