### PR TITLE
Updates for rocBLAS syr2k changes.

### PR DESCRIPTION
**Pull request by daineAMD**
Corresponding changes for https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/pull/1408

### CODE REVIEW

**Comment by daineAMD** [comment]
Looks like rocSOLVER found a bug in the updated rocblas syr2k code. It'll probably go away with https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/pull/1415, but the broken code is still around so I'll try to root cause it later tonight or monday morning.

**Comment by TorreZuk** [comment]
It looks like the test code also has a hidden TODO as we didn't have reference code for syrkx so used A==B.  Maybe should look at that now too.

**Comment by daineAMD** [comment]
Should be fixed after https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/pull/1418

**Comment by daineAMD** [comment]
Passing now after the rocBLAS fix.

**Review by TorreZuk — APPROVED** [review]
LGTM should try to merge ASAP so your other PRs can build again @jzuniga-amd

**Review by tfalders — APPROVED** [review]
Looks good, though there seem to be some test failures (memory access faults) that are unrelated to the bug in gemv. Are these the same failures you were seeing before?

**Comment by daineAMD** [comment]
@tfalders are you referring to the failures [in this CI run](http://math-ci.rocm.amd.com/blue/organizations/jenkins/compute-rocm-dkms-no-npi-hipclang%2Fprecheckin%2FrocSOLVER/detail/PR-463/3/pipeline)? If so, those are before the fix in rocBLAS. I [re-ran CI ](http://math-ci.rocm.amd.com/blue/organizations/jenkins/compute-rocm-dkms-no-npi-hipclang%2Fprecheckin%2FrocSOLVER/detail/PR-463/4/pipeline) which picks up the rocBLAS fix and it looks like it's all passing.

**Comment by tfalders** [comment]
> @tfalders are you referring to the failures [in this CI run](http://math-ci.rocm.amd.com/blue/organizations/jenkins/compute-rocm-dkms-no-npi-hipclang%2Fprecheckin%2FrocSOLVER/detail/PR-463/3/pipeline)? If so, those are before the fix in rocBLAS. I [re-ran CI ](http://math-ci.rocm.amd.com/blue/organizations/jenkins/compute-rocm-dkms-no-npi-hipclang%2Fprecheckin%2FrocSOLVER/detail/PR-463/4/pipeline) which picks up the rocBLAS fix and it looks like it's all passing.

Yes, that's what I was looking at. I didn't realize the new CI run hadn't finished yet lol.

**Comment by daineAMD** [comment]
CI is just waiting on a gfx1030 machine for pre-checkin. Everything else has passed. This PR is probably good to be merged by a rocSOLVER dev if you want to unblock other PRs, otherwise I've enabled auto-merge when CI machines are available.

**Pull request merged**
