### PR TITLE
Add cleanup option to install script

### PR DESCRIPTION
**Pull request by eidenyoshida**
Targeting large intermediate build directories to reduce stage 2 container size. Removing _CPack_Packages will save 3.9 gigabytes

### CODE REVIEW

**Comment by cgmb** [comment]
On my local machine, that appears to save 4GB. You could trim another ~2GB with a `make clean` (or if you would like to keep the generated binaries, a bit less with `find -name '*.o' -delete`).

**Review by cgmb — APPROVED** [review]

**Comment by cgmb** [comment]
LGTM. I only tested a debug build, but that went from 3.3G -> 1.1G.

**Review by jzuniga-amd — APPROVED** [review]
LGTM

**Review by tfalders — APPROVED** [review]
LGTM!

**Comment by cgmb** [comment]
@eidenyoshida, squash and merge whenever you're ready.

**Comment by cgmb** [comment]
I don't know how we missed this, but this change has significantly increased the build time for rocSOLVER on the CI. It would be fine if we did the build and the package creation in one go, but the CI does it as two steps, with the cleanup of the temporary files in the middle.

**Pull request merged**
