### PR TITLE
Use new recursive trmm template

### PR DESCRIPTION
**Pull request by tfalders**
Updates rocSOLVER to reflect changes introduced in https://github.com/ROCmSoftwarePlatform/rocBLAS-internal/pull/555.

The removal of a workspace for trmm allowed the removal of the work array for larfb, which cascaded to every function that calls larfb. The signatures for the affected template and memory size functions are not changed - only larfb.

### CODE REVIEW

**Comment by tfalders** [comment]
Per other discussions with @doctorcolinsmith, I should probably mention that the functions with changed signatures are not exposed in the public or private API. These are all internal routines.

**Review by cgmb — APPROVED** [review]
LGTM if tests pass.

**Review by jzuniga-amd — APPROVED** [review]
LGTM

**Comment by jzuniga-amd** [comment]
rocBLAS new latest successful build (with the new TRMM) is ready. I restarted  CI on this PR; It should pass now. Please merge asap to update other PRs and unblock builds.

**Pull request merged**
