### PR TITLE
Merge back hotfix #344 from master to develop

### PR DESCRIPTION
**Pull request by amcamd**
- merge back master branch hot-fix in PR# 344
- These change the rocBLAS internal API called by
  - rocblasCallGemm
  - rocblasCall_syr2k_her2k
- Note that this needs to be merged after rocBLAS-internal PR#979 . There may be some time where rocSOLVER and rocBLAS internal APIs differ.

### CODE REVIEW

**Review by TorreZuk — APPROVED** [review]
LGTM but tests may not pass until rocBLAS matching build is propagated over the weekend.

**Comment by tfalders** [comment]
This PR might not be needed as we will probably be rebasing develop onto master.

@jzuniga-amd @cgmb Thoughts?

**Comment by amcamd** [comment]
I think if you rebase develop on master in the ROCmSoftwarePlatforms fork you will need to force push to ROCmSoftwarePlatform and anyone with commits after a rebased commit ends up with a "detached head". I avoid rebasing outside of my fork. I never rebase or force push in the ROCmSoftwarePlatform fork, I do it frequently in my own fork.

**Comment by amcamd** [comment]
I have merged the accompanying rocBLAS-internal PR# 979 . I expect the rocSOLVER develop branch will fail until this PR is merged.

**Comment by amcamd** [comment]
I will wait till approval from the rocSOLVER team to merge this PR.

**Review by jzuniga-amd — APPROVED** [review]
LGTM
You can merge this one, Andrew, thanks!

**Review by tfalders — APPROVED** [review]
We decided to proceed with the merge this time since there are too many PRs to rebase. LGTM!

**Review by cgmb — APPROVED** [review]

**Pull request merged**
