### PR TITLE
Doc reorg

### PR DESCRIPTION
**Pull request by randyh62**
reorganized for diataxis: 
added card TOC structure
added Installation, How to, and Reference
removed Library Design
moved Contributing to How to 
moved Tuning performance to Reference

### CODE REVIEW

**Comment by randyh62** [comment]
This needs review and approval. Anyone up tot he task?

**Comment by jzuniga-amd** [comment]
I will look into this today.

**Review by jzuniga-amd — CHANGES_REQUESTED** [review]
I open a PR to your branch with some modifications and suggestions that are hard to convey via comments in a review. Please have a look and let me know. Once the suggested changes are merged or discussed I will finalize my review.

**Review by jzuniga-amd — APPROVED** [review]
LGTM. 
Please wait for a second review from the development team, and be sure to "squash & merge" so that only one commit is created. Thanks.

**Review by cgmb — APPROVED** [review]
LGTM

**Review by tfalders — APPROVED** [review]

**Comment by randyh62** [comment]
Thanks for your review.

**Pull request merged**
